# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AlbumStats(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, play_count: int=None, like_count: int=None, comment_count: int=None, rating_avg: float=None):  # noqa: E501
        """AlbumStats - a model defined in Swagger

        :param play_count: The play_count of this AlbumStats.  # noqa: E501
        :type play_count: int
        :param like_count: The like_count of this AlbumStats.  # noqa: E501
        :type like_count: int
        :param comment_count: The comment_count of this AlbumStats.  # noqa: E501
        :type comment_count: int
        :param rating_avg: The rating_avg of this AlbumStats.  # noqa: E501
        :type rating_avg: float
        """
        self.swagger_types = {
            'play_count': int,
            'like_count': int,
            'comment_count': int,
            'rating_avg': float
        }

        self.attribute_map = {
            'play_count': 'playCount',
            'like_count': 'likeCount',
            'comment_count': 'commentCount',
            'rating_avg': 'ratingAvg'
        }
        self._play_count = play_count
        self._like_count = like_count
        self._comment_count = comment_count
        self._rating_avg = rating_avg

    @classmethod
    def from_dict(cls, dikt) -> 'AlbumStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Album_stats of this AlbumStats.  # noqa: E501
        :rtype: AlbumStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def play_count(self) -> int:
        """Gets the play_count of this AlbumStats.


        :return: The play_count of this AlbumStats.
        :rtype: int
        """
        return self._play_count

    @play_count.setter
    def play_count(self, play_count: int):
        """Sets the play_count of this AlbumStats.


        :param play_count: The play_count of this AlbumStats.
        :type play_count: int
        """

        self._play_count = play_count

    @property
    def like_count(self) -> int:
        """Gets the like_count of this AlbumStats.


        :return: The like_count of this AlbumStats.
        :rtype: int
        """
        return self._like_count

    @like_count.setter
    def like_count(self, like_count: int):
        """Sets the like_count of this AlbumStats.


        :param like_count: The like_count of this AlbumStats.
        :type like_count: int
        """

        self._like_count = like_count

    @property
    def comment_count(self) -> int:
        """Gets the comment_count of this AlbumStats.


        :return: The comment_count of this AlbumStats.
        :rtype: int
        """
        return self._comment_count

    @comment_count.setter
    def comment_count(self, comment_count: int):
        """Sets the comment_count of this AlbumStats.


        :param comment_count: The comment_count of this AlbumStats.
        :type comment_count: int
        """

        self._comment_count = comment_count

    @property
    def rating_avg(self) -> float:
        """Gets the rating_avg of this AlbumStats.


        :return: The rating_avg of this AlbumStats.
        :rtype: float
        """
        return self._rating_avg

    @rating_avg.setter
    def rating_avg(self, rating_avg: float):
        """Sets the rating_avg of this AlbumStats.


        :param rating_avg: The rating_avg of this AlbumStats.
        :type rating_avg: float
        """

        self._rating_avg = rating_avg
