# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AlbumCreateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None, artist_id: str=None, label_id: str=None, release_date: date=None, price: float=None, currency: str=None, genres: List[str]=None, tags: List[str]=None):  # noqa: E501
        """AlbumCreateInput - a model defined in Swagger

        :param title: The title of this AlbumCreateInput.  # noqa: E501
        :type title: str
        :param description: The description of this AlbumCreateInput.  # noqa: E501
        :type description: str
        :param artist_id: The artist_id of this AlbumCreateInput.  # noqa: E501
        :type artist_id: str
        :param label_id: The label_id of this AlbumCreateInput.  # noqa: E501
        :type label_id: str
        :param release_date: The release_date of this AlbumCreateInput.  # noqa: E501
        :type release_date: date
        :param price: The price of this AlbumCreateInput.  # noqa: E501
        :type price: float
        :param currency: The currency of this AlbumCreateInput.  # noqa: E501
        :type currency: str
        :param genres: The genres of this AlbumCreateInput.  # noqa: E501
        :type genres: List[str]
        :param tags: The tags of this AlbumCreateInput.  # noqa: E501
        :type tags: List[str]
        """
        self.swagger_types = {
            'title': str,
            'description': str,
            'artist_id': str,
            'label_id': str,
            'release_date': date,
            'price': float,
            'currency': str,
            'genres': List[str],
            'tags': List[str]
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            'artist_id': 'artistId',
            'label_id': 'labelId',
            'release_date': 'releaseDate',
            'price': 'price',
            'currency': 'currency',
            'genres': 'genres',
            'tags': 'tags'
        }
        self._title = title
        self._description = description
        self._artist_id = artist_id
        self._label_id = label_id
        self._release_date = release_date
        self._price = price
        self._currency = currency
        self._genres = genres
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'AlbumCreateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlbumCreateInput of this AlbumCreateInput.  # noqa: E501
        :rtype: AlbumCreateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this AlbumCreateInput.


        :return: The title of this AlbumCreateInput.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this AlbumCreateInput.


        :param title: The title of this AlbumCreateInput.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this AlbumCreateInput.


        :return: The description of this AlbumCreateInput.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this AlbumCreateInput.


        :param description: The description of this AlbumCreateInput.
        :type description: str
        """

        self._description = description

    @property
    def artist_id(self) -> str:
        """Gets the artist_id of this AlbumCreateInput.


        :return: The artist_id of this AlbumCreateInput.
        :rtype: str
        """
        return self._artist_id

    @artist_id.setter
    def artist_id(self, artist_id: str):
        """Sets the artist_id of this AlbumCreateInput.


        :param artist_id: The artist_id of this AlbumCreateInput.
        :type artist_id: str
        """

        self._artist_id = artist_id

    @property
    def label_id(self) -> str:
        """Gets the label_id of this AlbumCreateInput.


        :return: The label_id of this AlbumCreateInput.
        :rtype: str
        """
        return self._label_id

    @label_id.setter
    def label_id(self, label_id: str):
        """Sets the label_id of this AlbumCreateInput.


        :param label_id: The label_id of this AlbumCreateInput.
        :type label_id: str
        """

        self._label_id = label_id

    @property
    def release_date(self) -> date:
        """Gets the release_date of this AlbumCreateInput.


        :return: The release_date of this AlbumCreateInput.
        :rtype: date
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date: date):
        """Sets the release_date of this AlbumCreateInput.


        :param release_date: The release_date of this AlbumCreateInput.
        :type release_date: date
        """

        self._release_date = release_date

    @property
    def price(self) -> float:
        """Gets the price of this AlbumCreateInput.


        :return: The price of this AlbumCreateInput.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this AlbumCreateInput.


        :param price: The price of this AlbumCreateInput.
        :type price: float
        """

        self._price = price

    @property
    def currency(self) -> str:
        """Gets the currency of this AlbumCreateInput.


        :return: The currency of this AlbumCreateInput.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this AlbumCreateInput.


        :param currency: The currency of this AlbumCreateInput.
        :type currency: str
        """

        self._currency = currency

    @property
    def genres(self) -> List[str]:
        """Gets the genres of this AlbumCreateInput.


        :return: The genres of this AlbumCreateInput.
        :rtype: List[str]
        """
        return self._genres

    @genres.setter
    def genres(self, genres: List[str]):
        """Sets the genres of this AlbumCreateInput.


        :param genres: The genres of this AlbumCreateInput.
        :type genres: List[str]
        """

        self._genres = genres

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this AlbumCreateInput.


        :return: The tags of this AlbumCreateInput.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this AlbumCreateInput.


        :param tags: The tags of this AlbumCreateInput.
        :type tags: List[str]
        """

        self._tags = tags
