# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.one_ofalbum_id_tracks_body_tracks import OneOfalbumIdTracksBodyTracks  # noqa: F401,E501
from swagger_server import util


class AlbumIdTracksBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tracks: OneOfalbumIdTracksBodyTracks=None):  # noqa: E501
        """AlbumIdTracksBody - a model defined in Swagger

        :param tracks: The tracks of this AlbumIdTracksBody.  # noqa: E501
        :type tracks: OneOfalbumIdTracksBodyTracks
        """
        self.swagger_types = {
            'tracks': OneOfalbumIdTracksBodyTracks
        }

        self.attribute_map = {
            'tracks': 'tracks'
        }
        self._tracks = tracks

    @classmethod
    def from_dict(cls, dikt) -> 'AlbumIdTracksBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The albumId_tracks_body of this AlbumIdTracksBody.  # noqa: E501
        :rtype: AlbumIdTracksBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tracks(self) -> OneOfalbumIdTracksBodyTracks:
        """Gets the tracks of this AlbumIdTracksBody.

        Array de trackIds o objetos de pista mínimos  # noqa: E501

        :return: The tracks of this AlbumIdTracksBody.
        :rtype: OneOfalbumIdTracksBodyTracks
        """
        return self._tracks

    @tracks.setter
    def tracks(self, tracks: OneOfalbumIdTracksBodyTracks):
        """Sets the tracks of this AlbumIdTracksBody.

        Array de trackIds o objetos de pista mínimos  # noqa: E501

        :param tracks: The tracks of this AlbumIdTracksBody.
        :type tracks: OneOfalbumIdTracksBodyTracks
        """

        self._tracks = tracks
