# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AlbumIdCoverBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file: str=None, alt: str=None):  # noqa: E501
        """AlbumIdCoverBody - a model defined in Swagger

        :param file: The file of this AlbumIdCoverBody.  # noqa: E501
        :type file: str
        :param alt: The alt of this AlbumIdCoverBody.  # noqa: E501
        :type alt: str
        """
        self.swagger_types = {
            'file': str,
            'alt': str
        }

        self.attribute_map = {
            'file': 'file',
            'alt': 'alt'
        }
        self._file = file
        self._alt = alt

    @classmethod
    def from_dict(cls, dikt) -> 'AlbumIdCoverBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The albumId_cover_body of this AlbumIdCoverBody.  # noqa: E501
        :rtype: AlbumIdCoverBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> str:
        """Gets the file of this AlbumIdCoverBody.


        :return: The file of this AlbumIdCoverBody.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this AlbumIdCoverBody.


        :param file: The file of this AlbumIdCoverBody.
        :type file: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file

    @property
    def alt(self) -> str:
        """Gets the alt of this AlbumIdCoverBody.

        Texto alternativo  # noqa: E501

        :return: The alt of this AlbumIdCoverBody.
        :rtype: str
        """
        return self._alt

    @alt.setter
    def alt(self, alt: str):
        """Sets the alt of this AlbumIdCoverBody.

        Texto alternativo  # noqa: E501

        :param alt: The alt of this AlbumIdCoverBody.
        :type alt: str
        """

        self._alt = alt
