# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.album_stats import AlbumStats  # noqa: F401,E501
from swagger_server.models.artist_ref import ArtistRef  # noqa: F401,E501
from swagger_server.models.image import Image  # noqa: F401,E501
from swagger_server.models.label_ref import LabelRef  # noqa: F401,E501
from swagger_server.models.track import Track  # noqa: F401,E501
from swagger_server import util


class Album(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, title: str=None, description: str=None, artist: ArtistRef=None, label: LabelRef=None, release_date: date=None, release_state: str=None, price: float=None, currency: str=None, genres: List[str]=None, tags: List[str]=None, cover: Image=None, tracks: List[Track]=None, stats: AlbumStats=None, created_at: datetime=None, updated_at: datetime=None):  # noqa: E501
        """Album - a model defined in Swagger

        :param id: The id of this Album.  # noqa: E501
        :type id: str
        :param title: The title of this Album.  # noqa: E501
        :type title: str
        :param description: The description of this Album.  # noqa: E501
        :type description: str
        :param artist: The artist of this Album.  # noqa: E501
        :type artist: ArtistRef
        :param label: The label of this Album.  # noqa: E501
        :type label: LabelRef
        :param release_date: The release_date of this Album.  # noqa: E501
        :type release_date: date
        :param release_state: The release_state of this Album.  # noqa: E501
        :type release_state: str
        :param price: The price of this Album.  # noqa: E501
        :type price: float
        :param currency: The currency of this Album.  # noqa: E501
        :type currency: str
        :param genres: The genres of this Album.  # noqa: E501
        :type genres: List[str]
        :param tags: The tags of this Album.  # noqa: E501
        :type tags: List[str]
        :param cover: The cover of this Album.  # noqa: E501
        :type cover: Image
        :param tracks: The tracks of this Album.  # noqa: E501
        :type tracks: List[Track]
        :param stats: The stats of this Album.  # noqa: E501
        :type stats: AlbumStats
        :param created_at: The created_at of this Album.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Album.  # noqa: E501
        :type updated_at: datetime
        """
        self.swagger_types = {
            'id': str,
            'title': str,
            'description': str,
            'artist': ArtistRef,
            'label': LabelRef,
            'release_date': date,
            'release_state': str,
            'price': float,
            'currency': str,
            'genres': List[str],
            'tags': List[str],
            'cover': Image,
            'tracks': List[Track],
            'stats': AlbumStats,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'description': 'description',
            'artist': 'artist',
            'label': 'label',
            'release_date': 'releaseDate',
            'release_state': 'releaseState',
            'price': 'price',
            'currency': 'currency',
            'genres': 'genres',
            'tags': 'tags',
            'cover': 'cover',
            'tracks': 'tracks',
            'stats': 'stats',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }
        self._id = id
        self._title = title
        self._description = description
        self._artist = artist
        self._label = label
        self._release_date = release_date
        self._release_state = release_state
        self._price = price
        self._currency = currency
        self._genres = genres
        self._tags = tags
        self._cover = cover
        self._tracks = tracks
        self._stats = stats
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Album':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Album of this Album.  # noqa: E501
        :rtype: Album
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Album.


        :return: The id of this Album.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Album.


        :param id: The id of this Album.
        :type id: str
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Album.


        :return: The title of this Album.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Album.


        :param title: The title of this Album.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this Album.


        :return: The description of this Album.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Album.


        :param description: The description of this Album.
        :type description: str
        """

        self._description = description

    @property
    def artist(self) -> ArtistRef:
        """Gets the artist of this Album.


        :return: The artist of this Album.
        :rtype: ArtistRef
        """
        return self._artist

    @artist.setter
    def artist(self, artist: ArtistRef):
        """Sets the artist of this Album.


        :param artist: The artist of this Album.
        :type artist: ArtistRef
        """

        self._artist = artist

    @property
    def label(self) -> LabelRef:
        """Gets the label of this Album.


        :return: The label of this Album.
        :rtype: LabelRef
        """
        return self._label

    @label.setter
    def label(self, label: LabelRef):
        """Sets the label of this Album.


        :param label: The label of this Album.
        :type label: LabelRef
        """

        self._label = label

    @property
    def release_date(self) -> date:
        """Gets the release_date of this Album.


        :return: The release_date of this Album.
        :rtype: date
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date: date):
        """Sets the release_date of this Album.


        :param release_date: The release_date of this Album.
        :type release_date: date
        """

        self._release_date = release_date

    @property
    def release_state(self) -> str:
        """Gets the release_state of this Album.


        :return: The release_state of this Album.
        :rtype: str
        """
        return self._release_state

    @release_state.setter
    def release_state(self, release_state: str):
        """Sets the release_state of this Album.


        :param release_state: The release_state of this Album.
        :type release_state: str
        """
        allowed_values = ["draft", "scheduled", "published", "archived"]  # noqa: E501
        if release_state not in allowed_values:
            raise ValueError(
                "Invalid value for `release_state` ({0}), must be one of {1}"
                .format(release_state, allowed_values)
            )

        self._release_state = release_state

    @property
    def price(self) -> float:
        """Gets the price of this Album.


        :return: The price of this Album.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Album.


        :param price: The price of this Album.
        :type price: float
        """

        self._price = price

    @property
    def currency(self) -> str:
        """Gets the currency of this Album.


        :return: The currency of this Album.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this Album.


        :param currency: The currency of this Album.
        :type currency: str
        """

        self._currency = currency

    @property
    def genres(self) -> List[str]:
        """Gets the genres of this Album.


        :return: The genres of this Album.
        :rtype: List[str]
        """
        return self._genres

    @genres.setter
    def genres(self, genres: List[str]):
        """Sets the genres of this Album.


        :param genres: The genres of this Album.
        :type genres: List[str]
        """

        self._genres = genres

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this Album.


        :return: The tags of this Album.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this Album.


        :param tags: The tags of this Album.
        :type tags: List[str]
        """

        self._tags = tags

    @property
    def cover(self) -> Image:
        """Gets the cover of this Album.


        :return: The cover of this Album.
        :rtype: Image
        """
        return self._cover

    @cover.setter
    def cover(self, cover: Image):
        """Sets the cover of this Album.


        :param cover: The cover of this Album.
        :type cover: Image
        """

        self._cover = cover

    @property
    def tracks(self) -> List[Track]:
        """Gets the tracks of this Album.


        :return: The tracks of this Album.
        :rtype: List[Track]
        """
        return self._tracks

    @tracks.setter
    def tracks(self, tracks: List[Track]):
        """Sets the tracks of this Album.


        :param tracks: The tracks of this Album.
        :type tracks: List[Track]
        """

        self._tracks = tracks

    @property
    def stats(self) -> AlbumStats:
        """Gets the stats of this Album.


        :return: The stats of this Album.
        :rtype: AlbumStats
        """
        return self._stats

    @stats.setter
    def stats(self, stats: AlbumStats):
        """Sets the stats of this Album.


        :param stats: The stats of this Album.
        :type stats: AlbumStats
        """

        self._stats = stats

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Album.


        :return: The created_at of this Album.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Album.


        :param created_at: The created_at of this Album.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Album.


        :return: The updated_at of this Album.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Album.


        :param updated_at: The updated_at of this Album.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
