# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.album import Album  # noqa: F401,E501
from swagger_server import util


class AlbumResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Album=None):  # noqa: E501
        """AlbumResponse - a model defined in Swagger

        :param data: The data of this AlbumResponse.  # noqa: E501
        :type data: Album
        """
        self.swagger_types = {
            'data': Album
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AlbumResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlbumResponse of this AlbumResponse.  # noqa: E501
        :rtype: AlbumResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Album:
        """Gets the data of this AlbumResponse.


        :return: The data of this AlbumResponse.
        :rtype: Album
        """
        return self._data

    @data.setter
    def data(self, data: Album):
        """Sets the data of this AlbumResponse.


        :param data: The data of this AlbumResponse.
        :type data: Album
        """

        self._data = data
