# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AlbumStatsData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_plays: int=None, plays_last7_days: int=None, plays_last30_days: int=None, rating_avg: float=None, sales_count: int=None):  # noqa: E501
        """AlbumStatsData - a model defined in Swagger

        :param total_plays: The total_plays of this AlbumStatsData.  # noqa: E501
        :type total_plays: int
        :param plays_last7_days: The plays_last7_days of this AlbumStatsData.  # noqa: E501
        :type plays_last7_days: int
        :param plays_last30_days: The plays_last30_days of this AlbumStatsData.  # noqa: E501
        :type plays_last30_days: int
        :param rating_avg: The rating_avg of this AlbumStatsData.  # noqa: E501
        :type rating_avg: float
        :param sales_count: The sales_count of this AlbumStatsData.  # noqa: E501
        :type sales_count: int
        """
        self.swagger_types = {
            'total_plays': int,
            'plays_last7_days': int,
            'plays_last30_days': int,
            'rating_avg': float,
            'sales_count': int
        }

        self.attribute_map = {
            'total_plays': 'totalPlays',
            'plays_last7_days': 'playsLast7Days',
            'plays_last30_days': 'playsLast30Days',
            'rating_avg': 'ratingAvg',
            'sales_count': 'salesCount'
        }
        self._total_plays = total_plays
        self._plays_last7_days = plays_last7_days
        self._plays_last30_days = plays_last30_days
        self._rating_avg = rating_avg
        self._sales_count = sales_count

    @classmethod
    def from_dict(cls, dikt) -> 'AlbumStatsData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlbumStats_data of this AlbumStatsData.  # noqa: E501
        :rtype: AlbumStatsData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_plays(self) -> int:
        """Gets the total_plays of this AlbumStatsData.


        :return: The total_plays of this AlbumStatsData.
        :rtype: int
        """
        return self._total_plays

    @total_plays.setter
    def total_plays(self, total_plays: int):
        """Sets the total_plays of this AlbumStatsData.


        :param total_plays: The total_plays of this AlbumStatsData.
        :type total_plays: int
        """

        self._total_plays = total_plays

    @property
    def plays_last7_days(self) -> int:
        """Gets the plays_last7_days of this AlbumStatsData.


        :return: The plays_last7_days of this AlbumStatsData.
        :rtype: int
        """
        return self._plays_last7_days

    @plays_last7_days.setter
    def plays_last7_days(self, plays_last7_days: int):
        """Sets the plays_last7_days of this AlbumStatsData.


        :param plays_last7_days: The plays_last7_days of this AlbumStatsData.
        :type plays_last7_days: int
        """

        self._plays_last7_days = plays_last7_days

    @property
    def plays_last30_days(self) -> int:
        """Gets the plays_last30_days of this AlbumStatsData.


        :return: The plays_last30_days of this AlbumStatsData.
        :rtype: int
        """
        return self._plays_last30_days

    @plays_last30_days.setter
    def plays_last30_days(self, plays_last30_days: int):
        """Sets the plays_last30_days of this AlbumStatsData.


        :param plays_last30_days: The plays_last30_days of this AlbumStatsData.
        :type plays_last30_days: int
        """

        self._plays_last30_days = plays_last30_days

    @property
    def rating_avg(self) -> float:
        """Gets the rating_avg of this AlbumStatsData.


        :return: The rating_avg of this AlbumStatsData.
        :rtype: float
        """
        return self._rating_avg

    @rating_avg.setter
    def rating_avg(self, rating_avg: float):
        """Sets the rating_avg of this AlbumStatsData.


        :param rating_avg: The rating_avg of this AlbumStatsData.
        :type rating_avg: float
        """

        self._rating_avg = rating_avg

    @property
    def sales_count(self) -> int:
        """Gets the sales_count of this AlbumStatsData.


        :return: The sales_count of this AlbumStatsData.
        :rtype: int
        """
        return self._sales_count

    @sales_count.setter
    def sales_count(self, sales_count: int):
        """Sets the sales_count of this AlbumStatsData.


        :param sales_count: The sales_count of this AlbumStatsData.
        :type sales_count: int
        """

        self._sales_count = sales_count
