# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CommentsCommentIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, text: str=None, status: str=None, rating: int=None):  # noqa: E501
        """CommentsCommentIdBody - a model defined in Swagger

        :param text: The text of this CommentsCommentIdBody.  # noqa: E501
        :type text: str
        :param status: The status of this CommentsCommentIdBody.  # noqa: E501
        :type status: str
        :param rating: The rating of this CommentsCommentIdBody.  # noqa: E501
        :type rating: int
        """
        self.swagger_types = {
            'text': str,
            'status': str,
            'rating': int
        }

        self.attribute_map = {
            'text': 'text',
            'status': 'status',
            'rating': 'rating'
        }
        self._text = text
        self._status = status
        self._rating = rating

    @classmethod
    def from_dict(cls, dikt) -> 'CommentsCommentIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The comments_commentId_body of this CommentsCommentIdBody.  # noqa: E501
        :rtype: CommentsCommentIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this CommentsCommentIdBody.


        :return: The text of this CommentsCommentIdBody.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this CommentsCommentIdBody.


        :param text: The text of this CommentsCommentIdBody.
        :type text: str
        """

        self._text = text

    @property
    def status(self) -> str:
        """Gets the status of this CommentsCommentIdBody.


        :return: The status of this CommentsCommentIdBody.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this CommentsCommentIdBody.


        :param status: The status of this CommentsCommentIdBody.
        :type status: str
        """
        allowed_values = ["visible", "hidden", "pending"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def rating(self) -> int:
        """Gets the rating of this CommentsCommentIdBody.


        :return: The rating of this CommentsCommentIdBody.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this CommentsCommentIdBody.


        :param rating: The rating of this CommentsCommentIdBody.
        :type rating: int
        """

        self._rating = rating
