# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Comment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, target_type: str=None, target_id: str=None, user_id: str=None, text: str=None, rating: int=None, status: str='visible', likes: int=0, created_at: datetime=None, updated_at: datetime=None, replies: List['Comment']=None):  # noqa: E501
        """Comment - a model defined in Swagger

        :param id: The id of this Comment.  # noqa: E501
        :type id: str
        :param target_type: The target_type of this Comment.  # noqa: E501
        :type target_type: str
        :param target_id: The target_id of this Comment.  # noqa: E501
        :type target_id: str
        :param user_id: The user_id of this Comment.  # noqa: E501
        :type user_id: str
        :param text: The text of this Comment.  # noqa: E501
        :type text: str
        :param rating: The rating of this Comment.  # noqa: E501
        :type rating: int
        :param status: The status of this Comment.  # noqa: E501
        :type status: str
        :param likes: The likes of this Comment.  # noqa: E501
        :type likes: int
        :param created_at: The created_at of this Comment.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Comment.  # noqa: E501
        :type updated_at: datetime
        :param replies: The replies of this Comment.  # noqa: E501
        :type replies: List['Comment']
        """
        self.swagger_types = {
            'id': str,
            'target_type': str,
            'target_id': str,
            'user_id': str,
            'text': str,
            'rating': int,
            'status': str,
            'likes': int,
            'created_at': datetime,
            'updated_at': datetime,
            'replies': List['Comment']
        }

        self.attribute_map = {
            'id': 'id',
            'target_type': 'targetType',
            'target_id': 'targetId',
            'user_id': 'userId',
            'text': 'text',
            'rating': 'rating',
            'status': 'status',
            'likes': 'likes',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt',
            'replies': 'replies'
        }
        self._id = id
        self._target_type = target_type
        self._target_id = target_id
        self._user_id = user_id
        self._text = text
        self._rating = rating
        self._status = status
        self._likes = likes
        self._created_at = created_at
        self._updated_at = updated_at
        self._replies = replies

    @classmethod
    def from_dict(cls, dikt) -> 'Comment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Comment of this Comment.  # noqa: E501
        :rtype: Comment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Comment.


        :return: The id of this Comment.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Comment.


        :param id: The id of this Comment.
        :type id: str
        """

        self._id = id

    @property
    def target_type(self) -> str:
        """Gets the target_type of this Comment.


        :return: The target_type of this Comment.
        :rtype: str
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type: str):
        """Sets the target_type of this Comment.


        :param target_type: The target_type of this Comment.
        :type target_type: str
        """
        allowed_values = ["album", "track", "merch"]  # noqa: E501
        if target_type not in allowed_values:
            raise ValueError(
                "Invalid value for `target_type` ({0}), must be one of {1}"
                .format(target_type, allowed_values)
            )

        self._target_type = target_type

    @property
    def target_id(self) -> str:
        """Gets the target_id of this Comment.


        :return: The target_id of this Comment.
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id: str):
        """Sets the target_id of this Comment.


        :param target_id: The target_id of this Comment.
        :type target_id: str
        """

        self._target_id = target_id

    @property
    def user_id(self) -> str:
        """Gets the user_id of this Comment.


        :return: The user_id of this Comment.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this Comment.


        :param user_id: The user_id of this Comment.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def text(self) -> str:
        """Gets the text of this Comment.


        :return: The text of this Comment.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Comment.


        :param text: The text of this Comment.
        :type text: str
        """

        self._text = text

    @property
    def rating(self) -> int:
        """Gets the rating of this Comment.


        :return: The rating of this Comment.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this Comment.


        :param rating: The rating of this Comment.
        :type rating: int
        """

        self._rating = rating

    @property
    def status(self) -> str:
        """Gets the status of this Comment.


        :return: The status of this Comment.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Comment.


        :param status: The status of this Comment.
        :type status: str
        """
        allowed_values = ["visible", "hidden", "pending"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def likes(self) -> int:
        """Gets the likes of this Comment.


        :return: The likes of this Comment.
        :rtype: int
        """
        return self._likes

    @likes.setter
    def likes(self, likes: int):
        """Sets the likes of this Comment.


        :param likes: The likes of this Comment.
        :type likes: int
        """

        self._likes = likes

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Comment.


        :return: The created_at of this Comment.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Comment.


        :param created_at: The created_at of this Comment.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Comment.


        :return: The updated_at of this Comment.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Comment.


        :param updated_at: The updated_at of this Comment.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def replies(self) -> List['Comment']:
        """Gets the replies of this Comment.


        :return: The replies of this Comment.
        :rtype: List['Comment']
        """
        return self._replies

    @replies.setter
    def replies(self, replies: List['Comment']):
        """Sets the replies of this Comment.


        :param replies: The replies of this Comment.
        :type replies: List['Comment']
        """

        self._replies = replies
