# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.comment import Comment  # noqa: F401,E501
from swagger_server import util


class CommentResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Comment=None):  # noqa: E501
        """CommentResponse - a model defined in Swagger

        :param data: The data of this CommentResponse.  # noqa: E501
        :type data: Comment
        """
        self.swagger_types = {
            'data': Comment
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CommentResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommentResponse of this CommentResponse.  # noqa: E501
        :rtype: CommentResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Comment:
        """Gets the data of this CommentResponse.


        :return: The data of this CommentResponse.
        :rtype: Comment
        """
        return self._data

    @data.setter
    def data(self, data: Comment):
        """Sets the data of this CommentResponse.


        :param data: The data of this CommentResponse.
        :type data: Comment
        """

        self._data = data
