# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CommentCreateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, target_type: str=None, target_id: str=None, text: str=None, rating: int=None):  # noqa: E501
        """CommentCreateInput - a model defined in Swagger

        :param target_type: The target_type of this CommentCreateInput.  # noqa: E501
        :type target_type: str
        :param target_id: The target_id of this CommentCreateInput.  # noqa: E501
        :type target_id: str
        :param text: The text of this CommentCreateInput.  # noqa: E501
        :type text: str
        :param rating: The rating of this CommentCreateInput.  # noqa: E501
        :type rating: int
        """
        self.swagger_types = {
            'target_type': str,
            'target_id': str,
            'text': str,
            'rating': int
        }

        self.attribute_map = {
            'target_type': 'targetType',
            'target_id': 'targetId',
            'text': 'text',
            'rating': 'rating'
        }
        self._target_type = target_type
        self._target_id = target_id
        self._text = text
        self._rating = rating

    @classmethod
    def from_dict(cls, dikt) -> 'CommentCreateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommentCreateInput of this CommentCreateInput.  # noqa: E501
        :rtype: CommentCreateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_type(self) -> str:
        """Gets the target_type of this CommentCreateInput.


        :return: The target_type of this CommentCreateInput.
        :rtype: str
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type: str):
        """Sets the target_type of this CommentCreateInput.


        :param target_type: The target_type of this CommentCreateInput.
        :type target_type: str
        """
        allowed_values = ["album", "track", "merch"]  # noqa: E501
        if target_type not in allowed_values:
            raise ValueError(
                "Invalid value for `target_type` ({0}), must be one of {1}"
                .format(target_type, allowed_values)
            )

        self._target_type = target_type

    @property
    def target_id(self) -> str:
        """Gets the target_id of this CommentCreateInput.


        :return: The target_id of this CommentCreateInput.
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id: str):
        """Sets the target_id of this CommentCreateInput.


        :param target_id: The target_id of this CommentCreateInput.
        :type target_id: str
        """

        self._target_id = target_id

    @property
    def text(self) -> str:
        """Gets the text of this CommentCreateInput.


        :return: The text of this CommentCreateInput.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this CommentCreateInput.


        :param text: The text of this CommentCreateInput.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def rating(self) -> int:
        """Gets the rating of this CommentCreateInput.


        :return: The rating of this CommentCreateInput.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this CommentCreateInput.


        :param rating: The rating of this CommentCreateInput.
        :type rating: int
        """

        self._rating = rating
