# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FavoritesMerchBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, merch_id: str=None):  # noqa: E501
        """FavoritesMerchBody - a model defined in Swagger

        :param merch_id: The merch_id of this FavoritesMerchBody.  # noqa: E501
        :type merch_id: str
        """
        self.swagger_types = {
            'merch_id': str
        }

        self.attribute_map = {
            'merch_id': 'merchId'
        }
        self._merch_id = merch_id

    @classmethod
    def from_dict(cls, dikt) -> 'FavoritesMerchBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The favorites_merch_body of this FavoritesMerchBody.  # noqa: E501
        :rtype: FavoritesMerchBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def merch_id(self) -> str:
        """Gets the merch_id of this FavoritesMerchBody.


        :return: The merch_id of this FavoritesMerchBody.
        :rtype: str
        """
        return self._merch_id

    @merch_id.setter
    def merch_id(self, merch_id: str):
        """Sets the merch_id of this FavoritesMerchBody.


        :param merch_id: The merch_id of this FavoritesMerchBody.
        :type merch_id: str
        """
        if merch_id is None:
            raise ValueError("Invalid value for `merch_id`, must not be `None`")  # noqa: E501

        self._merch_id = merch_id
