# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FavoritesAlbumsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, album_id: str=None):  # noqa: E501
        """FavoritesAlbumsBody - a model defined in Swagger

        :param album_id: The album_id of this FavoritesAlbumsBody.  # noqa: E501
        :type album_id: str
        """
        self.swagger_types = {
            'album_id': str
        }

        self.attribute_map = {
            'album_id': 'albumId'
        }
        self._album_id = album_id

    @classmethod
    def from_dict(cls, dikt) -> 'FavoritesAlbumsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The favorites_albums_body of this FavoritesAlbumsBody.  # noqa: E501
        :rtype: FavoritesAlbumsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def album_id(self) -> str:
        """Gets the album_id of this FavoritesAlbumsBody.


        :return: The album_id of this FavoritesAlbumsBody.
        :rtype: str
        """
        return self._album_id

    @album_id.setter
    def album_id(self, album_id: str):
        """Sets the album_id of this FavoritesAlbumsBody.


        :param album_id: The album_id of this FavoritesAlbumsBody.
        :type album_id: str
        """
        if album_id is None:
            raise ValueError("Invalid value for `album_id`, must not be `None`")  # noqa: E501

        self._album_id = album_id
