# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Image(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, alt: str=None, width: int=None, height: int=None):  # noqa: E501
        """Image - a model defined in Swagger

        :param url: The url of this Image.  # noqa: E501
        :type url: str
        :param alt: The alt of this Image.  # noqa: E501
        :type alt: str
        :param width: The width of this Image.  # noqa: E501
        :type width: int
        :param height: The height of this Image.  # noqa: E501
        :type height: int
        """
        self.swagger_types = {
            'url': str,
            'alt': str,
            'width': int,
            'height': int
        }

        self.attribute_map = {
            'url': 'url',
            'alt': 'alt',
            'width': 'width',
            'height': 'height'
        }
        self._url = url
        self._alt = alt
        self._width = width
        self._height = height

    @classmethod
    def from_dict(cls, dikt) -> 'Image':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Image of this Image.  # noqa: E501
        :rtype: Image
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this Image.


        :return: The url of this Image.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Image.


        :param url: The url of this Image.
        :type url: str
        """

        self._url = url

    @property
    def alt(self) -> str:
        """Gets the alt of this Image.


        :return: The alt of this Image.
        :rtype: str
        """
        return self._alt

    @alt.setter
    def alt(self, alt: str):
        """Sets the alt of this Image.


        :param alt: The alt of this Image.
        :type alt: str
        """

        self._alt = alt

    @property
    def width(self) -> int:
        """Gets the width of this Image.


        :return: The width of this Image.
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width: int):
        """Sets the width of this Image.


        :param width: The width of this Image.
        :type width: int
        """

        self._width = width

    @property
    def height(self) -> int:
        """Gets the height of this Image.


        :return: The height of this Image.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height: int):
        """Sets the height of this Image.


        :param height: The height of this Image.
        :type height: int
        """

        self._height = height
