# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, expires_at: datetime=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param url: The url of this InlineResponse200.  # noqa: E501
        :type url: str
        :param expires_at: The expires_at of this InlineResponse200.  # noqa: E501
        :type expires_at: datetime
        """
        self.swagger_types = {
            'url': str,
            'expires_at': datetime
        }

        self.attribute_map = {
            'url': 'url',
            'expires_at': 'expiresAt'
        }
        self._url = url
        self._expires_at = expires_at

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this InlineResponse200.


        :return: The url of this InlineResponse200.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this InlineResponse200.


        :param url: The url of this InlineResponse200.
        :type url: str
        """

        self._url = url

    @property
    def expires_at(self) -> datetime:
        """Gets the expires_at of this InlineResponse200.


        :return: The expires_at of this InlineResponse200.
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at: datetime):
        """Sets the expires_at of this InlineResponse200.


        :param expires_at: The expires_at of this InlineResponse200.
        :type expires_at: datetime
        """

        self._expires_at = expires_at
