# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.variant import Variant  # noqa: F401,E501
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Variant=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param data: The data of this InlineResponse201.  # noqa: E501
        :type data: Variant
        """
        self.swagger_types = {
            'data': Variant
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Variant:
        """Gets the data of this InlineResponse201.


        :return: The data of this InlineResponse201.
        :rtype: Variant
        """
        return self._data

    @data.setter
    def data(self, data: Variant):
        """Sets the data of this InlineResponse201.


        :param data: The data of this InlineResponse201.
        :type data: Variant
        """

        self._data = data
