# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.label import Label  # noqa: F401,E501
from swagger_server import util


class LabelResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Label=None):  # noqa: E501
        """LabelResponse - a model defined in Swagger

        :param data: The data of this LabelResponse.  # noqa: E501
        :type data: Label
        """
        self.swagger_types = {
            'data': Label
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'LabelResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LabelResponse of this LabelResponse.  # noqa: E501
        :rtype: LabelResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Label:
        """Gets the data of this LabelResponse.


        :return: The data of this LabelResponse.
        :rtype: Label
        """
        return self._data

    @data.setter
    def data(self, data: Label):
        """Sets the data of this LabelResponse.


        :param data: The data of this LabelResponse.
        :type data: Label
        """

        self._data = data
