# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.album import Album  # noqa: F401,E501
from swagger_server.models.artist_ref import ArtistRef  # noqa: F401,E501
from swagger_server import util


class Label(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, description: str=None, country: str=None, url: str=None, artists: List[ArtistRef]=None, albums: List[Album]=None, created_at: datetime=None, updated_at: datetime=None):  # noqa: E501
        """Label - a model defined in Swagger

        :param id: The id of this Label.  # noqa: E501
        :type id: str
        :param name: The name of this Label.  # noqa: E501
        :type name: str
        :param description: The description of this Label.  # noqa: E501
        :type description: str
        :param country: The country of this Label.  # noqa: E501
        :type country: str
        :param url: The url of this Label.  # noqa: E501
        :type url: str
        :param artists: The artists of this Label.  # noqa: E501
        :type artists: List[ArtistRef]
        :param albums: The albums of this Label.  # noqa: E501
        :type albums: List[Album]
        :param created_at: The created_at of this Label.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Label.  # noqa: E501
        :type updated_at: datetime
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'description': str,
            'country': str,
            'url': str,
            'artists': List[ArtistRef],
            'albums': List[Album],
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'country': 'country',
            'url': 'url',
            'artists': 'artists',
            'albums': 'albums',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }
        self._id = id
        self._name = name
        self._description = description
        self._country = country
        self._url = url
        self._artists = artists
        self._albums = albums
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Label':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Label of this Label.  # noqa: E501
        :rtype: Label
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Label.


        :return: The id of this Label.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Label.


        :param id: The id of this Label.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Label.


        :return: The name of this Label.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Label.


        :param name: The name of this Label.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Label.


        :return: The description of this Label.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Label.


        :param description: The description of this Label.
        :type description: str
        """

        self._description = description

    @property
    def country(self) -> str:
        """Gets the country of this Label.


        :return: The country of this Label.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this Label.


        :param country: The country of this Label.
        :type country: str
        """

        self._country = country

    @property
    def url(self) -> str:
        """Gets the url of this Label.


        :return: The url of this Label.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Label.


        :param url: The url of this Label.
        :type url: str
        """

        self._url = url

    @property
    def artists(self) -> List[ArtistRef]:
        """Gets the artists of this Label.


        :return: The artists of this Label.
        :rtype: List[ArtistRef]
        """
        return self._artists

    @artists.setter
    def artists(self, artists: List[ArtistRef]):
        """Sets the artists of this Label.


        :param artists: The artists of this Label.
        :type artists: List[ArtistRef]
        """

        self._artists = artists

    @property
    def albums(self) -> List[Album]:
        """Gets the albums of this Label.


        :return: The albums of this Label.
        :rtype: List[Album]
        """
        return self._albums

    @albums.setter
    def albums(self, albums: List[Album]):
        """Sets the albums of this Label.


        :param albums: The albums of this Label.
        :type albums: List[Album]
        """

        self._albums = albums

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Label.


        :return: The created_at of this Label.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Label.


        :param created_at: The created_at of this Label.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Label.


        :return: The updated_at of this Label.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Label.


        :param updated_at: The updated_at of this Label.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
