# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LabelCreateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, country: str=None, url: str=None):  # noqa: E501
        """LabelCreateInput - a model defined in Swagger

        :param name: The name of this LabelCreateInput.  # noqa: E501
        :type name: str
        :param description: The description of this LabelCreateInput.  # noqa: E501
        :type description: str
        :param country: The country of this LabelCreateInput.  # noqa: E501
        :type country: str
        :param url: The url of this LabelCreateInput.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'country': str,
            'url': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'country': 'country',
            'url': 'url'
        }
        self._name = name
        self._description = description
        self._country = country
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'LabelCreateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LabelCreateInput of this LabelCreateInput.  # noqa: E501
        :rtype: LabelCreateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this LabelCreateInput.


        :return: The name of this LabelCreateInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this LabelCreateInput.


        :param name: The name of this LabelCreateInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this LabelCreateInput.


        :return: The description of this LabelCreateInput.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this LabelCreateInput.


        :param description: The description of this LabelCreateInput.
        :type description: str
        """

        self._description = description

    @property
    def country(self) -> str:
        """Gets the country of this LabelCreateInput.


        :return: The country of this LabelCreateInput.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this LabelCreateInput.


        :param country: The country of this LabelCreateInput.
        :type country: str
        """

        self._country = country

    @property
    def url(self) -> str:
        """Gets the url of this LabelCreateInput.


        :return: The url of this LabelCreateInput.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this LabelCreateInput.


        :param url: The url of this LabelCreateInput.
        :type url: str
        """

        self._url = url
