# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LabelUpdateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, country: str=None, url: str=None):  # noqa: E501
        """LabelUpdateInput - a model defined in Swagger

        :param name: The name of this LabelUpdateInput.  # noqa: E501
        :type name: str
        :param description: The description of this LabelUpdateInput.  # noqa: E501
        :type description: str
        :param country: The country of this LabelUpdateInput.  # noqa: E501
        :type country: str
        :param url: The url of this LabelUpdateInput.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'country': str,
            'url': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'country': 'country',
            'url': 'url'
        }
        self._name = name
        self._description = description
        self._country = country
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'LabelUpdateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LabelUpdateInput of this LabelUpdateInput.  # noqa: E501
        :rtype: LabelUpdateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this LabelUpdateInput.


        :return: The name of this LabelUpdateInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this LabelUpdateInput.


        :param name: The name of this LabelUpdateInput.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this LabelUpdateInput.


        :return: The description of this LabelUpdateInput.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this LabelUpdateInput.


        :param description: The description of this LabelUpdateInput.
        :type description: str
        """

        self._description = description

    @property
    def country(self) -> str:
        """Gets the country of this LabelUpdateInput.


        :return: The country of this LabelUpdateInput.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this LabelUpdateInput.


        :param country: The country of this LabelUpdateInput.
        :type country: str
        """

        self._country = country

    @property
    def url(self) -> str:
        """Gets the url of this LabelUpdateInput.


        :return: The url of this LabelUpdateInput.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this LabelUpdateInput.


        :param url: The url of this LabelUpdateInput.
        :type url: str
        """

        self._url = url
