# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MerchUpdateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, type: str=None, artist_id: str=None, label_id: str=None, availability: str=None):  # noqa: E501
        """MerchUpdateInput - a model defined in Swagger

        :param name: The name of this MerchUpdateInput.  # noqa: E501
        :type name: str
        :param description: The description of this MerchUpdateInput.  # noqa: E501
        :type description: str
        :param type: The type of this MerchUpdateInput.  # noqa: E501
        :type type: str
        :param artist_id: The artist_id of this MerchUpdateInput.  # noqa: E501
        :type artist_id: str
        :param label_id: The label_id of this MerchUpdateInput.  # noqa: E501
        :type label_id: str
        :param availability: The availability of this MerchUpdateInput.  # noqa: E501
        :type availability: str
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'type': str,
            'artist_id': str,
            'label_id': str,
            'availability': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'type': 'type',
            'artist_id': 'artistId',
            'label_id': 'labelId',
            'availability': 'availability'
        }
        self._name = name
        self._description = description
        self._type = type
        self._artist_id = artist_id
        self._label_id = label_id
        self._availability = availability

    @classmethod
    def from_dict(cls, dikt) -> 'MerchUpdateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MerchUpdateInput of this MerchUpdateInput.  # noqa: E501
        :rtype: MerchUpdateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MerchUpdateInput.


        :return: The name of this MerchUpdateInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MerchUpdateInput.


        :param name: The name of this MerchUpdateInput.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this MerchUpdateInput.


        :return: The description of this MerchUpdateInput.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this MerchUpdateInput.


        :param description: The description of this MerchUpdateInput.
        :type description: str
        """

        self._description = description

    @property
    def type(self) -> str:
        """Gets the type of this MerchUpdateInput.


        :return: The type of this MerchUpdateInput.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this MerchUpdateInput.


        :param type: The type of this MerchUpdateInput.
        :type type: str
        """
        allowed_values = ["camiseta", "vinilo", "cd", "poster", "pegatina", "otro"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def artist_id(self) -> str:
        """Gets the artist_id of this MerchUpdateInput.


        :return: The artist_id of this MerchUpdateInput.
        :rtype: str
        """
        return self._artist_id

    @artist_id.setter
    def artist_id(self, artist_id: str):
        """Sets the artist_id of this MerchUpdateInput.


        :param artist_id: The artist_id of this MerchUpdateInput.
        :type artist_id: str
        """

        self._artist_id = artist_id

    @property
    def label_id(self) -> str:
        """Gets the label_id of this MerchUpdateInput.


        :return: The label_id of this MerchUpdateInput.
        :rtype: str
        """
        return self._label_id

    @label_id.setter
    def label_id(self, label_id: str):
        """Sets the label_id of this MerchUpdateInput.


        :param label_id: The label_id of this MerchUpdateInput.
        :type label_id: str
        """

        self._label_id = label_id

    @property
    def availability(self) -> str:
        """Gets the availability of this MerchUpdateInput.


        :return: The availability of this MerchUpdateInput.
        :rtype: str
        """
        return self._availability

    @availability.setter
    def availability(self, availability: str):
        """Sets the availability of this MerchUpdateInput.


        :param availability: The availability of this MerchUpdateInput.
        :type availability: str
        """
        allowed_values = ["in_stock", "out_of_stock", "preorder"]  # noqa: E501
        if availability not in allowed_values:
            raise ValueError(
                "Invalid value for `availability` ({0}), must be one of {1}"
                .format(availability, allowed_values)
            )

        self._availability = availability
