# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MerchIdImagesBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, files: List[str]=None, alt: str=None):  # noqa: E501
        """MerchIdImagesBody - a model defined in Swagger

        :param files: The files of this MerchIdImagesBody.  # noqa: E501
        :type files: List[str]
        :param alt: The alt of this MerchIdImagesBody.  # noqa: E501
        :type alt: str
        """
        self.swagger_types = {
            'files': List[str],
            'alt': str
        }

        self.attribute_map = {
            'files': 'files',
            'alt': 'alt'
        }
        self._files = files
        self._alt = alt

    @classmethod
    def from_dict(cls, dikt) -> 'MerchIdImagesBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The merchId_images_body of this MerchIdImagesBody.  # noqa: E501
        :rtype: MerchIdImagesBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def files(self) -> List[str]:
        """Gets the files of this MerchIdImagesBody.


        :return: The files of this MerchIdImagesBody.
        :rtype: List[str]
        """
        return self._files

    @files.setter
    def files(self, files: List[str]):
        """Sets the files of this MerchIdImagesBody.


        :param files: The files of this MerchIdImagesBody.
        :type files: List[str]
        """

        self._files = files

    @property
    def alt(self) -> str:
        """Gets the alt of this MerchIdImagesBody.


        :return: The alt of this MerchIdImagesBody.
        :rtype: str
        """
        return self._alt

    @alt.setter
    def alt(self, alt: str):
        """Sets the alt of this MerchIdImagesBody.


        :param alt: The alt of this MerchIdImagesBody.
        :type alt: str
        """

        self._alt = alt
