# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MerchCreateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, type: str=None, artist_id: str=None, label_id: str=None):  # noqa: E501
        """MerchCreateInput - a model defined in Swagger

        :param name: The name of this MerchCreateInput.  # noqa: E501
        :type name: str
        :param description: The description of this MerchCreateInput.  # noqa: E501
        :type description: str
        :param type: The type of this MerchCreateInput.  # noqa: E501
        :type type: str
        :param artist_id: The artist_id of this MerchCreateInput.  # noqa: E501
        :type artist_id: str
        :param label_id: The label_id of this MerchCreateInput.  # noqa: E501
        :type label_id: str
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'type': str,
            'artist_id': str,
            'label_id': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'type': 'type',
            'artist_id': 'artistId',
            'label_id': 'labelId'
        }
        self._name = name
        self._description = description
        self._type = type
        self._artist_id = artist_id
        self._label_id = label_id

    @classmethod
    def from_dict(cls, dikt) -> 'MerchCreateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MerchCreateInput of this MerchCreateInput.  # noqa: E501
        :rtype: MerchCreateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MerchCreateInput.


        :return: The name of this MerchCreateInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MerchCreateInput.


        :param name: The name of this MerchCreateInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this MerchCreateInput.


        :return: The description of this MerchCreateInput.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this MerchCreateInput.


        :param description: The description of this MerchCreateInput.
        :type description: str
        """

        self._description = description

    @property
    def type(self) -> str:
        """Gets the type of this MerchCreateInput.


        :return: The type of this MerchCreateInput.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this MerchCreateInput.


        :param type: The type of this MerchCreateInput.
        :type type: str
        """
        allowed_values = ["camiseta", "vinilo", "cd", "poster", "pegatina", "otro"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def artist_id(self) -> str:
        """Gets the artist_id of this MerchCreateInput.


        :return: The artist_id of this MerchCreateInput.
        :rtype: str
        """
        return self._artist_id

    @artist_id.setter
    def artist_id(self, artist_id: str):
        """Sets the artist_id of this MerchCreateInput.


        :param artist_id: The artist_id of this MerchCreateInput.
        :type artist_id: str
        """

        self._artist_id = artist_id

    @property
    def label_id(self) -> str:
        """Gets the label_id of this MerchCreateInput.


        :return: The label_id of this MerchCreateInput.
        :rtype: str
        """
        return self._label_id

    @label_id.setter
    def label_id(self, label_id: str):
        """Sets the label_id of this MerchCreateInput.


        :param label_id: The label_id of this MerchCreateInput.
        :type label_id: str
        """

        self._label_id = label_id
