# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.artist_ref import ArtistRef  # noqa: F401,E501
from swagger_server.models.image import Image  # noqa: F401,E501
from swagger_server.models.label_ref import LabelRef  # noqa: F401,E501
from swagger_server.models.variant import Variant  # noqa: F401,E501
from swagger_server import util


class MerchItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, description: str=None, type: str=None, images: List[Image]=None, variants: List[Variant]=None, label: LabelRef=None, artist: ArtistRef=None, availability: str=None, created_at: datetime=None, updated_at: datetime=None):  # noqa: E501
        """MerchItem - a model defined in Swagger

        :param id: The id of this MerchItem.  # noqa: E501
        :type id: str
        :param name: The name of this MerchItem.  # noqa: E501
        :type name: str
        :param description: The description of this MerchItem.  # noqa: E501
        :type description: str
        :param type: The type of this MerchItem.  # noqa: E501
        :type type: str
        :param images: The images of this MerchItem.  # noqa: E501
        :type images: List[Image]
        :param variants: The variants of this MerchItem.  # noqa: E501
        :type variants: List[Variant]
        :param label: The label of this MerchItem.  # noqa: E501
        :type label: LabelRef
        :param artist: The artist of this MerchItem.  # noqa: E501
        :type artist: ArtistRef
        :param availability: The availability of this MerchItem.  # noqa: E501
        :type availability: str
        :param created_at: The created_at of this MerchItem.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this MerchItem.  # noqa: E501
        :type updated_at: datetime
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'description': str,
            'type': str,
            'images': List[Image],
            'variants': List[Variant],
            'label': LabelRef,
            'artist': ArtistRef,
            'availability': str,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'type': 'type',
            'images': 'images',
            'variants': 'variants',
            'label': 'label',
            'artist': 'artist',
            'availability': 'availability',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }
        self._id = id
        self._name = name
        self._description = description
        self._type = type
        self._images = images
        self._variants = variants
        self._label = label
        self._artist = artist
        self._availability = availability
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'MerchItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MerchItem of this MerchItem.  # noqa: E501
        :rtype: MerchItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this MerchItem.


        :return: The id of this MerchItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this MerchItem.


        :param id: The id of this MerchItem.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this MerchItem.


        :return: The name of this MerchItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MerchItem.


        :param name: The name of this MerchItem.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this MerchItem.


        :return: The description of this MerchItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this MerchItem.


        :param description: The description of this MerchItem.
        :type description: str
        """

        self._description = description

    @property
    def type(self) -> str:
        """Gets the type of this MerchItem.


        :return: The type of this MerchItem.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this MerchItem.


        :param type: The type of this MerchItem.
        :type type: str
        """
        allowed_values = ["camiseta", "vinilo", "cd", "poster", "pegatina", "otro"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def images(self) -> List[Image]:
        """Gets the images of this MerchItem.


        :return: The images of this MerchItem.
        :rtype: List[Image]
        """
        return self._images

    @images.setter
    def images(self, images: List[Image]):
        """Sets the images of this MerchItem.


        :param images: The images of this MerchItem.
        :type images: List[Image]
        """

        self._images = images

    @property
    def variants(self) -> List[Variant]:
        """Gets the variants of this MerchItem.


        :return: The variants of this MerchItem.
        :rtype: List[Variant]
        """
        return self._variants

    @variants.setter
    def variants(self, variants: List[Variant]):
        """Sets the variants of this MerchItem.


        :param variants: The variants of this MerchItem.
        :type variants: List[Variant]
        """

        self._variants = variants

    @property
    def label(self) -> LabelRef:
        """Gets the label of this MerchItem.


        :return: The label of this MerchItem.
        :rtype: LabelRef
        """
        return self._label

    @label.setter
    def label(self, label: LabelRef):
        """Sets the label of this MerchItem.


        :param label: The label of this MerchItem.
        :type label: LabelRef
        """

        self._label = label

    @property
    def artist(self) -> ArtistRef:
        """Gets the artist of this MerchItem.


        :return: The artist of this MerchItem.
        :rtype: ArtistRef
        """
        return self._artist

    @artist.setter
    def artist(self, artist: ArtistRef):
        """Sets the artist of this MerchItem.


        :param artist: The artist of this MerchItem.
        :type artist: ArtistRef
        """

        self._artist = artist

    @property
    def availability(self) -> str:
        """Gets the availability of this MerchItem.


        :return: The availability of this MerchItem.
        :rtype: str
        """
        return self._availability

    @availability.setter
    def availability(self, availability: str):
        """Sets the availability of this MerchItem.


        :param availability: The availability of this MerchItem.
        :type availability: str
        """
        allowed_values = ["in_stock", "out_of_stock", "preorder"]  # noqa: E501
        if availability not in allowed_values:
            raise ValueError(
                "Invalid value for `availability` ({0}), must be one of {1}"
                .format(availability, allowed_values)
            )

        self._availability = availability

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this MerchItem.


        :return: The created_at of this MerchItem.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this MerchItem.


        :param created_at: The created_at of this MerchItem.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this MerchItem.


        :return: The updated_at of this MerchItem.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this MerchItem.


        :param updated_at: The updated_at of this MerchItem.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
