# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.merch_item import MerchItem  # noqa: F401,E501
from swagger_server import util


class MerchResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: MerchItem=None):  # noqa: E501
        """MerchResponse - a model defined in Swagger

        :param data: The data of this MerchResponse.  # noqa: E501
        :type data: MerchItem
        """
        self.swagger_types = {
            'data': MerchItem
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'MerchResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MerchResponse of this MerchResponse.  # noqa: E501
        :rtype: MerchResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> MerchItem:
        """Gets the data of this MerchResponse.


        :return: The data of this MerchResponse.
        :rtype: MerchItem
        """
        return self._data

    @data.setter
    def data(self, data: MerchItem):
        """Sets the data of this MerchResponse.


        :param data: The data of this MerchResponse.
        :type data: MerchItem
        """

        self._data = data
