# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PaginationMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, page: int=None, limit: int=None, total: int=None):  # noqa: E501
        """PaginationMeta - a model defined in Swagger

        :param page: The page of this PaginationMeta.  # noqa: E501
        :type page: int
        :param limit: The limit of this PaginationMeta.  # noqa: E501
        :type limit: int
        :param total: The total of this PaginationMeta.  # noqa: E501
        :type total: int
        """
        self.swagger_types = {
            'page': int,
            'limit': int,
            'total': int
        }

        self.attribute_map = {
            'page': 'page',
            'limit': 'limit',
            'total': 'total'
        }
        self._page = page
        self._limit = limit
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'PaginationMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaginationMeta of this PaginationMeta.  # noqa: E501
        :rtype: PaginationMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this PaginationMeta.


        :return: The page of this PaginationMeta.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this PaginationMeta.


        :param page: The page of this PaginationMeta.
        :type page: int
        """

        self._page = page

    @property
    def limit(self) -> int:
        """Gets the limit of this PaginationMeta.


        :return: The limit of this PaginationMeta.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this PaginationMeta.


        :param limit: The limit of this PaginationMeta.
        :type limit: int
        """

        self._limit = limit

    @property
    def total(self) -> int:
        """Gets the total of this PaginationMeta.


        :return: The total of this PaginationMeta.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this PaginationMeta.


        :param total: The total of this PaginationMeta.
        :type total: int
        """

        self._total = total
