# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.pagination_meta import PaginationMeta  # noqa: F401,E501
from swagger_server.models.track import Track  # noqa: F401,E501
from swagger_server import util


class PaginatedTrackList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[Track]=None, meta: PaginationMeta=None):  # noqa: E501
        """PaginatedTrackList - a model defined in Swagger

        :param data: The data of this PaginatedTrackList.  # noqa: E501
        :type data: List[Track]
        :param meta: The meta of this PaginatedTrackList.  # noqa: E501
        :type meta: PaginationMeta
        """
        self.swagger_types = {
            'data': List[Track],
            'meta': PaginationMeta
        }

        self.attribute_map = {
            'data': 'data',
            'meta': 'meta'
        }
        self._data = data
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'PaginatedTrackList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaginatedTrackList of this PaginatedTrackList.  # noqa: E501
        :rtype: PaginatedTrackList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Track]:
        """Gets the data of this PaginatedTrackList.


        :return: The data of this PaginatedTrackList.
        :rtype: List[Track]
        """
        return self._data

    @data.setter
    def data(self, data: List[Track]):
        """Sets the data of this PaginatedTrackList.


        :param data: The data of this PaginatedTrackList.
        :type data: List[Track]
        """

        self._data = data

    @property
    def meta(self) -> PaginationMeta:
        """Gets the meta of this PaginatedTrackList.


        :return: The meta of this PaginatedTrackList.
        :rtype: PaginationMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: PaginationMeta):
        """Sets the meta of this PaginatedTrackList.


        :param meta: The meta of this PaginatedTrackList.
        :type meta: PaginationMeta
        """

        self._meta = meta
