# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrackAudio(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, bitrate: int=None, codec: str=None):  # noqa: E501
        """TrackAudio - a model defined in Swagger

        :param url: The url of this TrackAudio.  # noqa: E501
        :type url: str
        :param bitrate: The bitrate of this TrackAudio.  # noqa: E501
        :type bitrate: int
        :param codec: The codec of this TrackAudio.  # noqa: E501
        :type codec: str
        """
        self.swagger_types = {
            'url': str,
            'bitrate': int,
            'codec': str
        }

        self.attribute_map = {
            'url': 'url',
            'bitrate': 'bitrate',
            'codec': 'codec'
        }
        self._url = url
        self._bitrate = bitrate
        self._codec = codec

    @classmethod
    def from_dict(cls, dikt) -> 'TrackAudio':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Track_audio of this TrackAudio.  # noqa: E501
        :rtype: TrackAudio
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this TrackAudio.


        :return: The url of this TrackAudio.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this TrackAudio.


        :param url: The url of this TrackAudio.
        :type url: str
        """

        self._url = url

    @property
    def bitrate(self) -> int:
        """Gets the bitrate of this TrackAudio.


        :return: The bitrate of this TrackAudio.
        :rtype: int
        """
        return self._bitrate

    @bitrate.setter
    def bitrate(self, bitrate: int):
        """Sets the bitrate of this TrackAudio.


        :param bitrate: The bitrate of this TrackAudio.
        :type bitrate: int
        """

        self._bitrate = bitrate

    @property
    def codec(self) -> str:
        """Gets the codec of this TrackAudio.


        :return: The codec of this TrackAudio.
        :rtype: str
        """
        return self._codec

    @codec.setter
    def codec(self, codec: str):
        """Sets the codec of this TrackAudio.


        :param codec: The codec of this TrackAudio.
        :type codec: str
        """

        self._codec = codec
