# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrackIdAudioBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file: str=None, bitrate: int=None, codec: str=None):  # noqa: E501
        """TrackIdAudioBody - a model defined in Swagger

        :param file: The file of this TrackIdAudioBody.  # noqa: E501
        :type file: str
        :param bitrate: The bitrate of this TrackIdAudioBody.  # noqa: E501
        :type bitrate: int
        :param codec: The codec of this TrackIdAudioBody.  # noqa: E501
        :type codec: str
        """
        self.swagger_types = {
            'file': str,
            'bitrate': int,
            'codec': str
        }

        self.attribute_map = {
            'file': 'file',
            'bitrate': 'bitrate',
            'codec': 'codec'
        }
        self._file = file
        self._bitrate = bitrate
        self._codec = codec

    @classmethod
    def from_dict(cls, dikt) -> 'TrackIdAudioBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The trackId_audio_body of this TrackIdAudioBody.  # noqa: E501
        :rtype: TrackIdAudioBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> str:
        """Gets the file of this TrackIdAudioBody.


        :return: The file of this TrackIdAudioBody.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this TrackIdAudioBody.


        :param file: The file of this TrackIdAudioBody.
        :type file: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file

    @property
    def bitrate(self) -> int:
        """Gets the bitrate of this TrackIdAudioBody.


        :return: The bitrate of this TrackIdAudioBody.
        :rtype: int
        """
        return self._bitrate

    @bitrate.setter
    def bitrate(self, bitrate: int):
        """Sets the bitrate of this TrackIdAudioBody.


        :param bitrate: The bitrate of this TrackIdAudioBody.
        :type bitrate: int
        """

        self._bitrate = bitrate

    @property
    def codec(self) -> str:
        """Gets the codec of this TrackIdAudioBody.


        :return: The codec of this TrackIdAudioBody.
        :rtype: str
        """
        return self._codec

    @codec.setter
    def codec(self, codec: str):
        """Sets the codec of this TrackIdAudioBody.


        :param codec: The codec of this TrackIdAudioBody.
        :type codec: str
        """

        self._codec = codec
