# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrackIdLyricsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, text: str=None, language: str=None):  # noqa: E501
        """TrackIdLyricsBody - a model defined in Swagger

        :param text: The text of this TrackIdLyricsBody.  # noqa: E501
        :type text: str
        :param language: The language of this TrackIdLyricsBody.  # noqa: E501
        :type language: str
        """
        self.swagger_types = {
            'text': str,
            'language': str
        }

        self.attribute_map = {
            'text': 'text',
            'language': 'language'
        }
        self._text = text
        self._language = language

    @classmethod
    def from_dict(cls, dikt) -> 'TrackIdLyricsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The trackId_lyrics_body of this TrackIdLyricsBody.  # noqa: E501
        :rtype: TrackIdLyricsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this TrackIdLyricsBody.


        :return: The text of this TrackIdLyricsBody.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this TrackIdLyricsBody.


        :param text: The text of this TrackIdLyricsBody.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def language(self) -> str:
        """Gets the language of this TrackIdLyricsBody.


        :return: The language of this TrackIdLyricsBody.
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language: str):
        """Sets the language of this TrackIdLyricsBody.


        :param language: The language of this TrackIdLyricsBody.
        :type language: str
        """

        self._language = language
