# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.track_create_minimal import TrackCreateMinimal  # noqa: F401,E501
from swagger_server import util


class TrackCreateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, album_id: str=None, label_id: str=None, track_number: int=None, tags: List[str]=None, title: str=None, duration_sec: int=None, artist_id: str=None):  # noqa: E501
        """TrackCreateInput - a model defined in Swagger

        :param album_id: The album_id of this TrackCreateInput.  # noqa: E501
        :type album_id: str
        :param label_id: The label_id of this TrackCreateInput.  # noqa: E501
        :type label_id: str
        :param track_number: The track_number of this TrackCreateInput.  # noqa: E501
        :type track_number: int
        :param tags: The tags of this TrackCreateInput.  # noqa: E501
        :type tags: List[str]
        :param title: The title of this TrackCreateInput.  # noqa: E501
        :type title: str
        :param duration_sec: The duration_sec of this TrackCreateInput.  # noqa: E501
        :type duration_sec: int
        :param artist_id: The artist_id of this TrackCreateInput.  # noqa: E501
        :type artist_id: str
        """
        self.swagger_types = {
            'album_id': str,
            'label_id': str,
            'track_number': int,
            'tags': List[str],
            'title': str,
            'duration_sec': int,
            'artist_id': str
        }

        self.attribute_map = {
            'album_id': 'albumId',
            'label_id': 'labelId',
            'track_number': 'trackNumber',
            'tags': 'tags',
            'title': 'title',
            'duration_sec': 'durationSec',
            'artist_id': 'artistId'
        }
        self._album_id = album_id
        self._label_id = label_id
        self._track_number = track_number
        self._tags = tags
        self._title = title
        self._duration_sec = duration_sec
        self._artist_id = artist_id

    @classmethod
    def from_dict(cls, dikt) -> 'TrackCreateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrackCreateInput of this TrackCreateInput.  # noqa: E501
        :rtype: TrackCreateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def album_id(self) -> str:
        """Gets the album_id of this TrackCreateInput.


        :return: The album_id of this TrackCreateInput.
        :rtype: str
        """
        return self._album_id

    @album_id.setter
    def album_id(self, album_id: str):
        """Sets the album_id of this TrackCreateInput.


        :param album_id: The album_id of this TrackCreateInput.
        :type album_id: str
        """

        self._album_id = album_id

    @property
    def label_id(self) -> str:
        """Gets the label_id of this TrackCreateInput.


        :return: The label_id of this TrackCreateInput.
        :rtype: str
        """
        return self._label_id

    @label_id.setter
    def label_id(self, label_id: str):
        """Sets the label_id of this TrackCreateInput.


        :param label_id: The label_id of this TrackCreateInput.
        :type label_id: str
        """

        self._label_id = label_id

    @property
    def track_number(self) -> int:
        """Gets the track_number of this TrackCreateInput.


        :return: The track_number of this TrackCreateInput.
        :rtype: int
        """
        return self._track_number

    @track_number.setter
    def track_number(self, track_number: int):
        """Sets the track_number of this TrackCreateInput.


        :param track_number: The track_number of this TrackCreateInput.
        :type track_number: int
        """

        self._track_number = track_number

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this TrackCreateInput.


        :return: The tags of this TrackCreateInput.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this TrackCreateInput.


        :param tags: The tags of this TrackCreateInput.
        :type tags: List[str]
        """

        self._tags = tags

    @property
    def title(self) -> str:
        """Gets the title of this TrackCreateInput.


        :return: The title of this TrackCreateInput.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this TrackCreateInput.


        :param title: The title of this TrackCreateInput.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def duration_sec(self) -> int:
        """Gets the duration_sec of this TrackCreateInput.


        :return: The duration_sec of this TrackCreateInput.
        :rtype: int
        """
        return self._duration_sec

    @duration_sec.setter
    def duration_sec(self, duration_sec: int):
        """Sets the duration_sec of this TrackCreateInput.


        :param duration_sec: The duration_sec of this TrackCreateInput.
        :type duration_sec: int
        """

        self._duration_sec = duration_sec

    @property
    def artist_id(self) -> str:
        """Gets the artist_id of this TrackCreateInput.


        :return: The artist_id of this TrackCreateInput.
        :rtype: str
        """
        return self._artist_id

    @artist_id.setter
    def artist_id(self, artist_id: str):
        """Sets the artist_id of this TrackCreateInput.


        :param artist_id: The artist_id of this TrackCreateInput.
        :type artist_id: str
        """

        self._artist_id = artist_id
