# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.album_ref import AlbumRef  # noqa: F401,E501
from swagger_server.models.artist_ref import ArtistRef  # noqa: F401,E501
from swagger_server.models.label_ref import LabelRef  # noqa: F401,E501
from swagger_server.models.track_audio import TrackAudio  # noqa: F401,E501
from swagger_server.models.track_lyrics import TrackLyrics  # noqa: F401,E501
from swagger_server.models.track_stats import TrackStats  # noqa: F401,E501
from swagger_server import util


class Track(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, title: str=None, duration_sec: int=None, track_number: int=None, artist: ArtistRef=None, album: AlbumRef=None, label: LabelRef=None, audio: TrackAudio=None, lyrics: TrackLyrics=None, stats: TrackStats=None, created_at: datetime=None, updated_at: datetime=None):  # noqa: E501
        """Track - a model defined in Swagger

        :param id: The id of this Track.  # noqa: E501
        :type id: str
        :param title: The title of this Track.  # noqa: E501
        :type title: str
        :param duration_sec: The duration_sec of this Track.  # noqa: E501
        :type duration_sec: int
        :param track_number: The track_number of this Track.  # noqa: E501
        :type track_number: int
        :param artist: The artist of this Track.  # noqa: E501
        :type artist: ArtistRef
        :param album: The album of this Track.  # noqa: E501
        :type album: AlbumRef
        :param label: The label of this Track.  # noqa: E501
        :type label: LabelRef
        :param audio: The audio of this Track.  # noqa: E501
        :type audio: TrackAudio
        :param lyrics: The lyrics of this Track.  # noqa: E501
        :type lyrics: TrackLyrics
        :param stats: The stats of this Track.  # noqa: E501
        :type stats: TrackStats
        :param created_at: The created_at of this Track.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Track.  # noqa: E501
        :type updated_at: datetime
        """
        self.swagger_types = {
            'id': str,
            'title': str,
            'duration_sec': int,
            'track_number': int,
            'artist': ArtistRef,
            'album': AlbumRef,
            'label': LabelRef,
            'audio': TrackAudio,
            'lyrics': TrackLyrics,
            'stats': TrackStats,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'duration_sec': 'durationSec',
            'track_number': 'trackNumber',
            'artist': 'artist',
            'album': 'album',
            'label': 'label',
            'audio': 'audio',
            'lyrics': 'lyrics',
            'stats': 'stats',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }
        self._id = id
        self._title = title
        self._duration_sec = duration_sec
        self._track_number = track_number
        self._artist = artist
        self._album = album
        self._label = label
        self._audio = audio
        self._lyrics = lyrics
        self._stats = stats
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Track':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Track of this Track.  # noqa: E501
        :rtype: Track
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Track.


        :return: The id of this Track.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Track.


        :param id: The id of this Track.
        :type id: str
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Track.


        :return: The title of this Track.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Track.


        :param title: The title of this Track.
        :type title: str
        """

        self._title = title

    @property
    def duration_sec(self) -> int:
        """Gets the duration_sec of this Track.


        :return: The duration_sec of this Track.
        :rtype: int
        """
        return self._duration_sec

    @duration_sec.setter
    def duration_sec(self, duration_sec: int):
        """Sets the duration_sec of this Track.


        :param duration_sec: The duration_sec of this Track.
        :type duration_sec: int
        """

        self._duration_sec = duration_sec

    @property
    def track_number(self) -> int:
        """Gets the track_number of this Track.


        :return: The track_number of this Track.
        :rtype: int
        """
        return self._track_number

    @track_number.setter
    def track_number(self, track_number: int):
        """Sets the track_number of this Track.


        :param track_number: The track_number of this Track.
        :type track_number: int
        """

        self._track_number = track_number

    @property
    def artist(self) -> ArtistRef:
        """Gets the artist of this Track.


        :return: The artist of this Track.
        :rtype: ArtistRef
        """
        return self._artist

    @artist.setter
    def artist(self, artist: ArtistRef):
        """Sets the artist of this Track.


        :param artist: The artist of this Track.
        :type artist: ArtistRef
        """

        self._artist = artist

    @property
    def album(self) -> AlbumRef:
        """Gets the album of this Track.


        :return: The album of this Track.
        :rtype: AlbumRef
        """
        return self._album

    @album.setter
    def album(self, album: AlbumRef):
        """Sets the album of this Track.


        :param album: The album of this Track.
        :type album: AlbumRef
        """

        self._album = album

    @property
    def label(self) -> LabelRef:
        """Gets the label of this Track.


        :return: The label of this Track.
        :rtype: LabelRef
        """
        return self._label

    @label.setter
    def label(self, label: LabelRef):
        """Sets the label of this Track.


        :param label: The label of this Track.
        :type label: LabelRef
        """

        self._label = label

    @property
    def audio(self) -> TrackAudio:
        """Gets the audio of this Track.


        :return: The audio of this Track.
        :rtype: TrackAudio
        """
        return self._audio

    @audio.setter
    def audio(self, audio: TrackAudio):
        """Sets the audio of this Track.


        :param audio: The audio of this Track.
        :type audio: TrackAudio
        """

        self._audio = audio

    @property
    def lyrics(self) -> TrackLyrics:
        """Gets the lyrics of this Track.


        :return: The lyrics of this Track.
        :rtype: TrackLyrics
        """
        return self._lyrics

    @lyrics.setter
    def lyrics(self, lyrics: TrackLyrics):
        """Sets the lyrics of this Track.


        :param lyrics: The lyrics of this Track.
        :type lyrics: TrackLyrics
        """

        self._lyrics = lyrics

    @property
    def stats(self) -> TrackStats:
        """Gets the stats of this Track.


        :return: The stats of this Track.
        :rtype: TrackStats
        """
        return self._stats

    @stats.setter
    def stats(self, stats: TrackStats):
        """Sets the stats of this Track.


        :param stats: The stats of this Track.
        :type stats: TrackStats
        """

        self._stats = stats

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Track.


        :return: The created_at of this Track.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Track.


        :param created_at: The created_at of this Track.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Track.


        :return: The updated_at of this Track.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Track.


        :param updated_at: The updated_at of this Track.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
