# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.track import Track  # noqa: F401,E501
from swagger_server import util


class TrackResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Track=None):  # noqa: E501
        """TrackResponse - a model defined in Swagger

        :param data: The data of this TrackResponse.  # noqa: E501
        :type data: Track
        """
        self.swagger_types = {
            'data': Track
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'TrackResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrackResponse of this TrackResponse.  # noqa: E501
        :rtype: TrackResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Track:
        """Gets the data of this TrackResponse.


        :return: The data of this TrackResponse.
        :rtype: Track
        """
        return self._data

    @data.setter
    def data(self, data: Track):
        """Sets the data of this TrackResponse.


        :param data: The data of this TrackResponse.
        :type data: Track
        """

        self._data = data
