# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrackStats(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, play_count: int=None):  # noqa: E501
        """TrackStats - a model defined in Swagger

        :param play_count: The play_count of this TrackStats.  # noqa: E501
        :type play_count: int
        """
        self.swagger_types = {
            'play_count': int
        }

        self.attribute_map = {
            'play_count': 'playCount'
        }
        self._play_count = play_count

    @classmethod
    def from_dict(cls, dikt) -> 'TrackStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Track_stats of this TrackStats.  # noqa: E501
        :rtype: TrackStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def play_count(self) -> int:
        """Gets the play_count of this TrackStats.


        :return: The play_count of this TrackStats.
        :rtype: int
        """
        return self._play_count

    @play_count.setter
    def play_count(self, play_count: int):
        """Sets the play_count of this TrackStats.


        :param play_count: The play_count of this TrackStats.
        :type play_count: int
        """

        self._play_count = play_count
