# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrackCreateMinimal(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, duration_sec: int=None, artist_id: str=None):  # noqa: E501
        """TrackCreateMinimal - a model defined in Swagger

        :param title: The title of this TrackCreateMinimal.  # noqa: E501
        :type title: str
        :param duration_sec: The duration_sec of this TrackCreateMinimal.  # noqa: E501
        :type duration_sec: int
        :param artist_id: The artist_id of this TrackCreateMinimal.  # noqa: E501
        :type artist_id: str
        """
        self.swagger_types = {
            'title': str,
            'duration_sec': int,
            'artist_id': str
        }

        self.attribute_map = {
            'title': 'title',
            'duration_sec': 'durationSec',
            'artist_id': 'artistId'
        }
        self._title = title
        self._duration_sec = duration_sec
        self._artist_id = artist_id

    @classmethod
    def from_dict(cls, dikt) -> 'TrackCreateMinimal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrackCreateMinimal of this TrackCreateMinimal.  # noqa: E501
        :rtype: TrackCreateMinimal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this TrackCreateMinimal.


        :return: The title of this TrackCreateMinimal.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this TrackCreateMinimal.


        :param title: The title of this TrackCreateMinimal.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def duration_sec(self) -> int:
        """Gets the duration_sec of this TrackCreateMinimal.


        :return: The duration_sec of this TrackCreateMinimal.
        :rtype: int
        """
        return self._duration_sec

    @duration_sec.setter
    def duration_sec(self, duration_sec: int):
        """Sets the duration_sec of this TrackCreateMinimal.


        :param duration_sec: The duration_sec of this TrackCreateMinimal.
        :type duration_sec: int
        """

        self._duration_sec = duration_sec

    @property
    def artist_id(self) -> str:
        """Gets the artist_id of this TrackCreateMinimal.


        :return: The artist_id of this TrackCreateMinimal.
        :rtype: str
        """
        return self._artist_id

    @artist_id.setter
    def artist_id(self, artist_id: str):
        """Sets the artist_id of this TrackCreateMinimal.


        :param artist_id: The artist_id of this TrackCreateMinimal.
        :type artist_id: str
        """

        self._artist_id = artist_id
