# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrackUpdateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, duration_sec: int=None, track_number: int=None, album_id: str=None, label_id: str=None, tags: List[str]=None):  # noqa: E501
        """TrackUpdateInput - a model defined in Swagger

        :param title: The title of this TrackUpdateInput.  # noqa: E501
        :type title: str
        :param duration_sec: The duration_sec of this TrackUpdateInput.  # noqa: E501
        :type duration_sec: int
        :param track_number: The track_number of this TrackUpdateInput.  # noqa: E501
        :type track_number: int
        :param album_id: The album_id of this TrackUpdateInput.  # noqa: E501
        :type album_id: str
        :param label_id: The label_id of this TrackUpdateInput.  # noqa: E501
        :type label_id: str
        :param tags: The tags of this TrackUpdateInput.  # noqa: E501
        :type tags: List[str]
        """
        self.swagger_types = {
            'title': str,
            'duration_sec': int,
            'track_number': int,
            'album_id': str,
            'label_id': str,
            'tags': List[str]
        }

        self.attribute_map = {
            'title': 'title',
            'duration_sec': 'durationSec',
            'track_number': 'trackNumber',
            'album_id': 'albumId',
            'label_id': 'labelId',
            'tags': 'tags'
        }
        self._title = title
        self._duration_sec = duration_sec
        self._track_number = track_number
        self._album_id = album_id
        self._label_id = label_id
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'TrackUpdateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrackUpdateInput of this TrackUpdateInput.  # noqa: E501
        :rtype: TrackUpdateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this TrackUpdateInput.


        :return: The title of this TrackUpdateInput.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this TrackUpdateInput.


        :param title: The title of this TrackUpdateInput.
        :type title: str
        """

        self._title = title

    @property
    def duration_sec(self) -> int:
        """Gets the duration_sec of this TrackUpdateInput.


        :return: The duration_sec of this TrackUpdateInput.
        :rtype: int
        """
        return self._duration_sec

    @duration_sec.setter
    def duration_sec(self, duration_sec: int):
        """Sets the duration_sec of this TrackUpdateInput.


        :param duration_sec: The duration_sec of this TrackUpdateInput.
        :type duration_sec: int
        """

        self._duration_sec = duration_sec

    @property
    def track_number(self) -> int:
        """Gets the track_number of this TrackUpdateInput.


        :return: The track_number of this TrackUpdateInput.
        :rtype: int
        """
        return self._track_number

    @track_number.setter
    def track_number(self, track_number: int):
        """Sets the track_number of this TrackUpdateInput.


        :param track_number: The track_number of this TrackUpdateInput.
        :type track_number: int
        """

        self._track_number = track_number

    @property
    def album_id(self) -> str:
        """Gets the album_id of this TrackUpdateInput.


        :return: The album_id of this TrackUpdateInput.
        :rtype: str
        """
        return self._album_id

    @album_id.setter
    def album_id(self, album_id: str):
        """Sets the album_id of this TrackUpdateInput.


        :param album_id: The album_id of this TrackUpdateInput.
        :type album_id: str
        """

        self._album_id = album_id

    @property
    def label_id(self) -> str:
        """Gets the label_id of this TrackUpdateInput.


        :return: The label_id of this TrackUpdateInput.
        :rtype: str
        """
        return self._label_id

    @label_id.setter
    def label_id(self, label_id: str):
        """Sets the label_id of this TrackUpdateInput.


        :param label_id: The label_id of this TrackUpdateInput.
        :type label_id: str
        """

        self._label_id = label_id

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this TrackUpdateInput.


        :return: The tags of this TrackUpdateInput.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this TrackUpdateInput.


        :param tags: The tags of this TrackUpdateInput.
        :type tags: List[str]
        """

        self._tags = tags
