# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Variant(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, sku: str=None, color: str=None, size: str=None, price: float=None, currency: str=None, stock: int=None):  # noqa: E501
        """Variant - a model defined in Swagger

        :param id: The id of this Variant.  # noqa: E501
        :type id: str
        :param sku: The sku of this Variant.  # noqa: E501
        :type sku: str
        :param color: The color of this Variant.  # noqa: E501
        :type color: str
        :param size: The size of this Variant.  # noqa: E501
        :type size: str
        :param price: The price of this Variant.  # noqa: E501
        :type price: float
        :param currency: The currency of this Variant.  # noqa: E501
        :type currency: str
        :param stock: The stock of this Variant.  # noqa: E501
        :type stock: int
        """
        self.swagger_types = {
            'id': str,
            'sku': str,
            'color': str,
            'size': str,
            'price': float,
            'currency': str,
            'stock': int
        }

        self.attribute_map = {
            'id': 'id',
            'sku': 'sku',
            'color': 'color',
            'size': 'size',
            'price': 'price',
            'currency': 'currency',
            'stock': 'stock'
        }
        self._id = id
        self._sku = sku
        self._color = color
        self._size = size
        self._price = price
        self._currency = currency
        self._stock = stock

    @classmethod
    def from_dict(cls, dikt) -> 'Variant':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Variant of this Variant.  # noqa: E501
        :rtype: Variant
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Variant.


        :return: The id of this Variant.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Variant.


        :param id: The id of this Variant.
        :type id: str
        """

        self._id = id

    @property
    def sku(self) -> str:
        """Gets the sku of this Variant.


        :return: The sku of this Variant.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku: str):
        """Sets the sku of this Variant.


        :param sku: The sku of this Variant.
        :type sku: str
        """

        self._sku = sku

    @property
    def color(self) -> str:
        """Gets the color of this Variant.


        :return: The color of this Variant.
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color: str):
        """Sets the color of this Variant.


        :param color: The color of this Variant.
        :type color: str
        """

        self._color = color

    @property
    def size(self) -> str:
        """Gets the size of this Variant.


        :return: The size of this Variant.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this Variant.


        :param size: The size of this Variant.
        :type size: str
        """

        self._size = size

    @property
    def price(self) -> float:
        """Gets the price of this Variant.


        :return: The price of this Variant.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Variant.


        :param price: The price of this Variant.
        :type price: float
        """

        self._price = price

    @property
    def currency(self) -> str:
        """Gets the currency of this Variant.


        :return: The currency of this Variant.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this Variant.


        :param currency: The currency of this Variant.
        :type currency: str
        """

        self._currency = currency

    @property
    def stock(self) -> int:
        """Gets the stock of this Variant.


        :return: The stock of this Variant.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this Variant.


        :param stock: The stock of this Variant.
        :type stock: int
        """

        self._stock = stock
