# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VariantUpdateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, price: float=None, currency: str=None, stock: int=None):  # noqa: E501
        """VariantUpdateInput - a model defined in Swagger

        :param price: The price of this VariantUpdateInput.  # noqa: E501
        :type price: float
        :param currency: The currency of this VariantUpdateInput.  # noqa: E501
        :type currency: str
        :param stock: The stock of this VariantUpdateInput.  # noqa: E501
        :type stock: int
        """
        self.swagger_types = {
            'price': float,
            'currency': str,
            'stock': int
        }

        self.attribute_map = {
            'price': 'price',
            'currency': 'currency',
            'stock': 'stock'
        }
        self._price = price
        self._currency = currency
        self._stock = stock

    @classmethod
    def from_dict(cls, dikt) -> 'VariantUpdateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VariantUpdateInput of this VariantUpdateInput.  # noqa: E501
        :rtype: VariantUpdateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price(self) -> float:
        """Gets the price of this VariantUpdateInput.


        :return: The price of this VariantUpdateInput.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this VariantUpdateInput.


        :param price: The price of this VariantUpdateInput.
        :type price: float
        """

        self._price = price

    @property
    def currency(self) -> str:
        """Gets the currency of this VariantUpdateInput.


        :return: The currency of this VariantUpdateInput.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this VariantUpdateInput.


        :param currency: The currency of this VariantUpdateInput.
        :type currency: str
        """

        self._currency = currency

    @property
    def stock(self) -> int:
        """Gets the stock of this VariantUpdateInput.


        :return: The stock of this VariantUpdateInput.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this VariantUpdateInput.


        :param stock: The stock of this VariantUpdateInput.
        :type stock: int
        """

        self._stock = stock
