# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VariantCreateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sku: str=None, color: str=None, size: str=None, price: float=None, currency: str=None, stock: int=None):  # noqa: E501
        """VariantCreateInput - a model defined in Swagger

        :param sku: The sku of this VariantCreateInput.  # noqa: E501
        :type sku: str
        :param color: The color of this VariantCreateInput.  # noqa: E501
        :type color: str
        :param size: The size of this VariantCreateInput.  # noqa: E501
        :type size: str
        :param price: The price of this VariantCreateInput.  # noqa: E501
        :type price: float
        :param currency: The currency of this VariantCreateInput.  # noqa: E501
        :type currency: str
        :param stock: The stock of this VariantCreateInput.  # noqa: E501
        :type stock: int
        """
        self.swagger_types = {
            'sku': str,
            'color': str,
            'size': str,
            'price': float,
            'currency': str,
            'stock': int
        }

        self.attribute_map = {
            'sku': 'sku',
            'color': 'color',
            'size': 'size',
            'price': 'price',
            'currency': 'currency',
            'stock': 'stock'
        }
        self._sku = sku
        self._color = color
        self._size = size
        self._price = price
        self._currency = currency
        self._stock = stock

    @classmethod
    def from_dict(cls, dikt) -> 'VariantCreateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VariantCreateInput of this VariantCreateInput.  # noqa: E501
        :rtype: VariantCreateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sku(self) -> str:
        """Gets the sku of this VariantCreateInput.


        :return: The sku of this VariantCreateInput.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku: str):
        """Sets the sku of this VariantCreateInput.


        :param sku: The sku of this VariantCreateInput.
        :type sku: str
        """

        self._sku = sku

    @property
    def color(self) -> str:
        """Gets the color of this VariantCreateInput.


        :return: The color of this VariantCreateInput.
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color: str):
        """Sets the color of this VariantCreateInput.


        :param color: The color of this VariantCreateInput.
        :type color: str
        """

        self._color = color

    @property
    def size(self) -> str:
        """Gets the size of this VariantCreateInput.


        :return: The size of this VariantCreateInput.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this VariantCreateInput.


        :param size: The size of this VariantCreateInput.
        :type size: str
        """

        self._size = size

    @property
    def price(self) -> float:
        """Gets the price of this VariantCreateInput.


        :return: The price of this VariantCreateInput.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this VariantCreateInput.


        :param price: The price of this VariantCreateInput.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def currency(self) -> str:
        """Gets the currency of this VariantCreateInput.


        :return: The currency of this VariantCreateInput.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this VariantCreateInput.


        :param currency: The currency of this VariantCreateInput.
        :type currency: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501

        self._currency = currency

    @property
    def stock(self) -> int:
        """Gets the stock of this VariantCreateInput.


        :return: The stock of this VariantCreateInput.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this VariantCreateInput.


        :param stock: The stock of this VariantCreateInput.
        :type stock: int
        """

        self._stock = stock
